# Generated by Django 3.0.6 on 2020-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200730_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
